spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5000/stockvet}
    username: ${DB_USERNAME:stockvet}
    password: ${DB_PASSWORD:stockvet}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:hRg2nzthwKbldOyO6tMRfmP0KOGZo04SuggwrCP71gg}
  expiration: ${JWT_EXPIRATION:3600000}
